# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b671934e1651ec2d03a77fd1c4da23a96b0e2350eb978651f0eae93f3f4b1c4cc47500799ace97d5563a881294c42f04b2e39b585d6a062bbca189e839d63cd4

test:
  secret_key_base: eb8bfbc49d7c4e479a07384691bce8cda118219b49263952fff7bff84460e29d8e665703d576454e14728cc5eeb62d35738f3797773c7156531fc6107da2aa40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
