secret = "UfOoUHYBZ3rUNWkSEnaV0g3Pv+fZHOCFSWELQ24t2oHLcS0w9kq8o6R4I5f7nLxbdGFxIjEH5m9S1Eb8+yZV8Ag8SeMW2dkGoKEZv3mQMgUlAxr9iVw1Q8y0DWb4LGc7IRD4vm4MQTonIiiLvNj3VRURQ3wNhqw1D/tjS0urTP51Sj1k2FnMhIbLdlqfOl0vPgzUE0w2qC7MfBLZ69hUDSnKI7aPU9eX3zdtNN9d2qwv3UrDEOzge7lSjVRNgFF79n9cBn3bg6Jhm5mBUjAwZfYit9F1DNb0r1UzSo6ZFoVjagTLPLmf4syM7Z3Ny9sH+342AjwrI0+XHMshiWdlPf+OuFIZJbHt1aVe6fbaXj9SlKt1Ja4cyOgtjkRYexbefQLL1kMMS9HSFyBsXV1IB4/c9sU6iafq1jwEwmvrTFquJfmqJliOobYv9fmj9zcGw/VL/luoagh11iorYVy1VVAEn/gD3QHyX6Au/iVKPYKgb++It5ZveYwi2kXWhQBxgpYXWm3569H4KJXszyAytVme15YXmA3B3cbDS0kjlPYnMteHbcLaFdMEnTY+9d88aKCDNfTmvdGfUy5xW+hX70ofLlQs75goFWGI91XWlrDXi0LsIkldwUKGTxPv3kFnVn7J1BqlWj5wWZCEXWY2psvegCpxmOucFSrDXJoBCn0="

[http]
  domain = "localhost"
  port = 3000
  ssl = false

[storage]
  type = "local"
  [storage.extra]
    root = "/var/www/attachments"
    url = "http://localhost/attachments"

[database]
  adapter = "postgres"
  host = "localhost"
  port = 5432
  name = "itpkg_reading_dev"
  user = "postgres"
  password = ""
  [database.extra]
    sslmode = "disable"

[redis]
  host = "localhost"
  port = 6379
  db = 1

[elastic_search]
  host = "localhost"
  port = 9200
  index = "itpkg_reading_dev"
